-- Enable crypto helpers for future use.
create extension if not exists pgcrypto;

create table if not exists public.candidates (
  id text primary key,
  name text not null,
  image text not null,
  department text not null,
  role text not null,
  description text not null,
  vote_count bigint not null default 0,
  is_trending boolean not null default false,
  rank integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  candidate_id text not null references public.candidates(id) on delete cascade,
  device_hash text not null,
  ip_hash text not null,
  ua_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists votes_candidate_idx on public.votes (candidate_id);
create index if not exists votes_device_created_idx on public.votes (device_hash, created_at desc);
create index if not exists votes_ip_created_idx on public.votes (ip_hash, created_at desc);

alter table public.candidates enable row level security;
alter table public.votes enable row level security;

drop policy if exists "candidates are readable" on public.candidates;
create policy "candidates are readable"
on public.candidates
for select
to anon, authenticated
using (true);

insert into public.candidates (id, name, image, department, role, description, vote_count, is_trending, rank)
values
  ('1', 'Sarah Miller', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBhDq3a9HA0YW7vH8RLY3QmlKkIWphHqM-C7FcPUNi6UGch1IzdFHHfrQpTOHS6_maS4I6gnCsIK7g7CJ2DvD4Yz8QcAzeDvtzVJFEpR3QheEJvOK1N1oZ41Fs1hs2I8wJE1lOpX_ilgfKrOdcnGIT8Kx--2L65jLbrOpgRmslVcquGReN5mQnRetWNWxyMUnW_WRoyjw94gDIUgGBKrDmMEdcFT6XQpLYjFMQbJQ14sZIILoC-VS7AaqSDdoh_8ASGfvRbmyfwt6t', 'Arts Dept', 'Senior', 'Sarah is a community volunteer and an aspiring digital artist known for her warm spirit.', 12450, true, null),
  ('2', 'Sophia Rose', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDS4bXVuLHRUOlxTGNjeA9Cbr8cEUu7UixKYXwoKyF-8auPNBuwt-R9o7dlpdnzp_Ye6wqj21syUoQro9JAO4INd3Ardhz9MeQ24TtvaoUhcNUe_ga2nUfMHPk3CgPYTkgq8P9L4o08oX-GvZGvr9DKgpoZvdYLB0-FPx6hepjmTHZcfg6uE7Wcd9-orGSi-gDabBID7g51BdOvzbPQJJ1ZFebSmHxUfQ6cDvoTRaA5nQaQG4CWwe1W1JUWENt7mouMfgjfQCo0dC7', 'Humanities', 'Junior', 'Launching the "Kind Hearts Initiative" to provide mental health resources.', 12482, false, 2),
  ('3', 'Chloe Chen', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAssyAzSM_Hk7bVFDybj8IYNxy04JwnXmGYqLgYO5CBV1oERs67ZUCMYwlXxGAYqfWEst8MxWCQSA16r5h1NdQbqKljS_sY150q_9iwtHJyfldeIZAgqt11InHfWeLxRJNIk5WVjerIvOG8cK7Su58XOjvjF7ZFJcJwRUht9UA238hf-1mGh69dwYuD0Sywls95OEtVVJ5AXqFVMmJWzPGc1rAiVey6GfxM7MUvzkMD3N5F_WghJt3IRbuV9ro_v-psHmx-1eqUe2H4', 'Music Dept', 'Freshman', 'A talented violinist who organizes free concerts for the elderly.', 9890, false, null),
  ('4', 'Elena Rodriguez', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLau3FeodBE7gxlqbvwtM53RiS_jzr4FbOryTnKZdfheGY_8BJ_TZOytXVqtb6cYsc4goUmrmpx9O2ZmtGVD6qUMBO4l0RhTKyfewtMVPKcLvXhZnhE4kCJTh45dWv5gY3KNXDXx4SLVHNYgHhgI48UEZAHpQeeb-ketwwfdz7jGby3GhIhh4mmS1w_URgH_deMgftj-skADeZXLSCijHkVKmPH9xpKAgEbrijpPgHjUfKTSFbRVS1cE4chLYfuHbcGyah1SXZbSNu', 'Science Dept', 'Junior', 'A science enthusiast who leads the environmental club and mentors younger students.', 942, false, null),
  ('5', 'Isabella Gray', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBcrCwLOmYlwlb0GyAFECt-NlHDVsegAl9uwCFiqAheumABAYzsNLOPNhUfdzBidtbdzGFB1NzHdd9YsXhb-fWeY-HDZJeCB0s7SlMxWexWW2AlxAcWRubwDPnwmFftqdI4vlpix7RIREIQyjRyzPGLEWjioxruU9-fl9BSxbsyBEBom8UYLsCPvirKRxroUoqzL251cQEZAn6tSkrvFnQF8EDYVKsPNk0P62ylg64Qjrouli9o60u7o7iDGqGZVViI_UYESYogwkLt', 'Psychology', 'Senior', 'Isabella is known for her empathy and works as a student counselor.', 890, false, null),
  ('6', 'Maya Thompson', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAFBkQNVnNemmHLDAzBmhp_ec_RLTNAlhNFx8-G5pxx5dlNE9WI_x9D_1Zb3QFBusooNnTMhoFTLF3EFUYD5jEs8OqkyIDkZsIc21_vCaB6CR-kNVt5yDWyR2LIvHCMDUczBcdYSuAFhz6P2RWow2Jx-ckwWPrwxa-eY8n62hGe5XGNxa3haouYeIakmHlGBWczVFXMN04jXo9GDElGHibbg37Gcy91pektvYIDzzLjnOKBg_8lc0XCe6SAwXHP_XgIVK0c5xL1vCvh', 'Business Dept', 'Senior', 'President of the Debate Team and a passionate advocate for student rights.', 756, false, null),
  ('7', 'Sophia Lauren', 'https://lh3.googleusercontent.com/aida-public/AB6AXuChcsZ2o1le1jA4lgm4y4N96ddsueRRjdPWwTOpcvu569fm7WErevZkG_cgtGFkhhUsChPlo-jeWCjAJ5P9PTcB4yS37xqZG3TBfPoJ0WIjmoTKhcsImPfiNMgVQ1NYWUnNgbmltUuMfqKEOuAuJ_nOzIM6spgI_gh31gxp5oSQK7ZicGjsh1LqSKgLg0o0-JPYQ5XQMn89UEnlHMX0Z855u57g3knDJfsyNDqWrZAnjwrIqwP4QhxsCMqh4Ln1ksa6cro_TZfBqu7P', 'Fashion', 'Sophomore', 'A trendsetter who organizes charity fashion shows for local orphanages.', 432, false, null),
  ('8', 'Clara Mendez', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSKhUdXLWeMS2yUrVG2qdiJwZdJ1bSL3qNw4L-LdWInnBBs3WFKyJwFlI0BGrA7S-Yhi6wr0Mdh2k0UXolqDtGlI2y1B04MTKMlEhaByXYequR6w84rP7CtY2vXX5jo1A1qzJrAfwJOMlKUAd8uyHc3UngtEbHdLZWqtVo217gvyOOuOl1o8hxOJzrlr_T4MO3f-m-JvEyblbYKT9mznfdTxrwhS4bRMURPVOZ8qjNcCYoICXb_Ux-8gYHzjg7FPaUNqaes_k4OWt4', 'Engineering', 'Junior', 'Robotics team captain with a heart of gold.', 9890, false, null)
on conflict (id) do update set
  name = excluded.name,
  image = excluded.image,
  department = excluded.department,
  role = excluded.role,
  description = excluded.description,
  vote_count = excluded.vote_count,
  is_trending = excluded.is_trending,
  rank = excluded.rank,
  updated_at = now();

create or replace function public.cast_vote(
  p_candidate_id text,
  p_device_hash text,
  p_ip_hash text,
  p_ua_hash text
)
returns table(status text, message text, vote_count bigint, voted_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_last_vote_at timestamptz;
  v_device_count integer;
  v_ip_count integer;
  v_vote_count bigint;
begin
  if p_candidate_id is null or p_candidate_id = '' then
    return query select 'invalid', 'Candidate is required.', 0::bigint, v_now;
    return;
  end if;

  if p_device_hash is null or p_device_hash = '' then
    return query select 'invalid', 'Device fingerprint is missing.', 0::bigint, v_now;
    return;
  end if;

  if p_ip_hash is null or p_ip_hash = '' then
    return query select 'invalid', 'IP fingerprint is missing.', 0::bigint, v_now;
    return;
  end if;

  if not exists (select 1 from public.candidates where id = p_candidate_id) then
    return query select 'not_found', 'Candidate not found.', 0::bigint, v_now;
    return;
  end if;

  select created_at
  into v_last_vote_at
  from public.votes
  where device_hash = p_device_hash
  order by created_at desc
  limit 1;

  if v_last_vote_at is not null and v_now - v_last_vote_at < interval '10 seconds' then
    return query select 'rate_limited', 'Please wait a few seconds before voting again.', 0::bigint, v_last_vote_at;
    return;
  end if;

  select count(*)
  into v_device_count
  from public.votes
  where device_hash = p_device_hash
    and created_at >= v_now - interval '24 hours';

  if v_device_count >= 10 then
    return query select 'rate_limited', 'Device vote limit reached for the last 24 hours.', 0::bigint, v_now;
    return;
  end if;

  select count(*)
  into v_ip_count
  from public.votes
  where ip_hash = p_ip_hash
    and created_at >= v_now - interval '24 hours';

  if v_ip_count >= 40 then
    return query select 'rate_limited', 'IP vote limit reached for the last 24 hours.', 0::bigint, v_now;
    return;
  end if;

  if exists (
    select 1
    from public.votes
    where candidate_id = p_candidate_id
      and device_hash = p_device_hash
      and created_at >= v_now - interval '24 hours'
  ) then
    select c.vote_count
    into v_vote_count
    from public.candidates as c
    where c.id = p_candidate_id;
    return query select 'already_voted', 'You already voted for this candidate in the last 24 hours.', coalesce(v_vote_count, 0), v_now;
    return;
  end if;

  insert into public.votes (candidate_id, device_hash, ip_hash, ua_hash, created_at)
  values (p_candidate_id, p_device_hash, p_ip_hash, p_ua_hash, v_now);

  update public.candidates as c
  set vote_count = c.vote_count + 1,
      updated_at = now()
  where c.id = p_candidate_id
  returning c.vote_count into v_vote_count;

  return query select 'ok', 'Vote recorded successfully.', v_vote_count, v_now;
end;
$$;

grant execute on function public.cast_vote(text, text, text, text) to anon, authenticated;
